[package]
name = "pqc-algo"
version = "0.1.0"
edition = "2021"

[dependencies]
oqs = "0.10"
rand = "0.8"
zeroize = { version = "1.7", features = ["derive"] }
aes-gcm = "0.10"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"

[dev-dependencies]
hex = "0.4"
